package io.github.a2asdk.spring.boot.starter.a2a.executor;

import io.a2a.server.agentexecution.AgentExecutor;
import io.a2a.server.agentexecution.RequestContext;
import io.a2a.server.events.EventQueue;
import io.a2a.server.tasks.TaskUpdater;
import io.a2a.spec.InternalError;
import io.a2a.spec.JSONRPCError;
import io.a2a.spec.Task;
import io.a2a.spec.TaskNotCancelableError;
import io.a2a.spec.TaskState;
import io.a2a.spec.TextPart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Default implementation of {@link AgentExecutor}.
 * 
 * This implementation provides basic task processing with echo-style responses.
 * It demonstrates proper use of {@link RequestContext} and {@link EventQueue}
 * for task lifecycle management.
 * 
 * <p>For production use, provide your own {@link AgentExecutor} implementation
 * by defining a bean:
 * <pre>{@code
 * @Component
 * public class MyAgentExecutor implements AgentExecutor {
 *     @Override
 *     public void execute(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
 *         TaskUpdater updater = new TaskUpdater(context, eventQueue);
 *         updater.submit();
 *         updater.startWork();
 *         
 *         // Your custom logic here
 *         String message = extractText(context.getMessage());
 *         String result = process(message);
 *         
 *         updater.addArtifact(List.of(new TextPart(result, null)), "response", "Result", null);
 *         updater.complete();
 *     }
 *     
 *     @Override
 *     public void cancel(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
 *         // Handle cancellation
 *     }
 * }
 * }</pre>
 * 
 * @see AgentExecutor
 * @see RequestContext
 * @see EventQueue
 */
public class DefaultAgentExecutor implements AgentExecutor {

    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultAgentExecutor.class);

    @Override
    public void execute(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
        TaskUpdater updater = new TaskUpdater(context, eventQueue);
        
        try {
            LOGGER.info("Starting task execution - taskId: {}, contextId: {}", 
                    context.getTaskId(), context.getContextId());
            
            if (context.getTask() == null) {
                updater.submit();
                LOGGER.debug("Task submitted");
            }
            
            updater.startWork();
            LOGGER.debug("Task status changed to WORKING");
            
            String userMessage = extractTextFromMessage(context.getMessage());
            LOGGER.info("Processing user message: {}", userMessage);
            
            String result = processMessage(userMessage);
            
            List<io.a2a.spec.Part<?>> parts = List.of(new TextPart(result, null));
            updater.addArtifact(parts, "response", "Agent Response", null);
            LOGGER.debug("Artifact added");
            
            updater.complete();
            LOGGER.info("Task completed successfully");
            
        } catch (JSONRPCError e) {
            LOGGER.error("JSONRPC error during task execution: {}", e.getMessage(), e);
            throw e;
        } catch (Exception e) {
            LOGGER.error("Unexpected error during task execution", e);
            throw new InternalError("Task execution failed: " + e.getMessage());
        }
    }

    @Override
    public void cancel(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
        Task task = context.getTask();
        
        if (task == null) {
            throw new TaskNotCancelableError("Task not found");
        }
        
        TaskState currentState = task.getStatus().state();
        if (currentState.isFinal()) {
            throw new TaskNotCancelableError(
                    "Task cannot be canceled - current state: " + currentState.asString());
        }
        
        TaskUpdater updater = new TaskUpdater(context, eventQueue);
        updater.cancel();
        LOGGER.info("Task canceled - taskId: {}", context.getTaskId());
    }

    /**
     * Process the user message and generate a response.
     * Override this method to implement custom logic.
     *
     * @param message the user's message text
     * @return the response text
     */
    protected String processMessage(String message) {
        return "Processed: " + message + "\n\nThis response was generated by the Spring A2A Agent.";
    }

    /**
     * Extract text content from a message.
     *
     * @param message the message
     * @return concatenated text content
     */
    protected String extractTextFromMessage(io.a2a.spec.Message message) {
        if (message == null || message.getParts() == null) {
            return "";
        }
        
        StringBuilder textBuilder = new StringBuilder();
        for (io.a2a.spec.Part<?> part : message.getParts()) {
            if (part instanceof TextPart textPart) {
                if (textBuilder.length() > 0) {
                    textBuilder.append(" ");
                }
                textBuilder.append(textPart.getText());
            }
        }
        return textBuilder.toString();
    }
}
