package io.github.a2asdk.spring.boot.starter.a2a.executor;

import io.a2a.spec.Message;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Simple default implementation of {@link A2AExecutor}.
 * 
 * This implementation provides a basic echo-style response.
 * It is used as a fallback when no custom executor is provided.
 * 
 * For production use, implement your own {@link A2AExecutor}.
 */
public class SimpleA2AExecutor implements A2AExecutor {

    private static final Logger LOGGER = LoggerFactory.getLogger(SimpleA2AExecutor.class);

    @Override
    public String execute(String taskId, Message message) {
        String userMessage = extractText(message);
        LOGGER.info("Processing task {} with message: {}", taskId, userMessage);
        
        return "Processed: " + userMessage + "\n\nThis response was generated by the Spring A2A Agent.";
    }
}
