package com.example.a2aspring.executor;

import io.a2a.server.agentexecution.RequestContext;
import io.a2a.server.events.EventQueue;
import io.a2a.server.tasks.TaskUpdater;
import io.a2a.spec.InternalError;
import io.a2a.spec.JSONRPCError;
import io.a2a.spec.Part;
import io.a2a.spec.TextPart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public class CustomBusinessAgentExecutor extends SpringAgentExecutor {

    private static final Logger LOGGER = LoggerFactory.getLogger(CustomBusinessAgentExecutor.class);

    @Override
    protected String processMessage(String message) {
        String lowerMessage = message.toLowerCase();
        
        if (lowerMessage.contains("analyze") || lowerMessage.contains("analysis")) {
            return performAnalysis(message);
        } else if (lowerMessage.contains("summarize") || lowerMessage.contains("summary")) {
            return performSummarization(message);
        } else if (lowerMessage.contains("transform") || lowerMessage.contains("convert")) {
            return performTransformation(message);
        } else {
            return generateGenericResponse(message);
        }
    }

    private String performAnalysis(String message) {
        LOGGER.info("Performing analysis for: {}", message);
        
        return """
                ## Analysis Results
                
                **Input:** %s
                
                **Analysis Type:** Content Analysis
                
                **Key Findings:**
                - Input length: %d characters
                - Word count: %d words
                - Complexity level: %s
                
                **Recommendations:**
                1. Consider breaking down complex requests
                2. Provide specific context for better results
                3. Use structured format for data processing
                
                **Processing completed by Spring A2A Agent**
                """.formatted(
                    message,
                    message.length(),
                    message.split("\\s+").length,
                    message.length() > 100 ? "High" : "Low"
                );
    }

    private String performSummarization(String message) {
        LOGGER.info("Performing summarization");
        
        String[] sentences = message.split("[.!?]+");
        StringBuilder summary = new StringBuilder();
        summary.append("## Summary\n\n");
        summary.append("**Original Length:** ").append(sentences.length).append(" sentences\n\n");
        summary.append("**Key Points:**\n");
        
        int count = 0;
        for (String sentence : sentences) {
            String trimmed = sentence.trim();
            if (!trimmed.isEmpty() && count < 3) {
                summary.append("- ").append(trimmed).append("\n");
                count++;
            }
        }
        
        summary.append("\n**Generated by Spring A2A Agent**");
        return summary.toString();
    }

    private String performTransformation(String message) {
        LOGGER.info("Performing transformation");
        
        return """
                ## Transformation Results
                
                **Original Input:**
                %s
                
                **Transformed Output:**
                ```
                %s
                ```
                
                **Operations Applied:**
                - Uppercase conversion
                - Character count: %d
                - Reversed: %s
                
                **Processed by Spring A2A Agent**
                """.formatted(
                    message,
                    message.toUpperCase(),
                    message.length(),
                    new StringBuilder(message).reverse().toString()
                );
    }

    private String generateGenericResponse(String message) {
        return """
                ## Response
                
                You said: "%s"
                
                I'm a Spring Boot integrated A2A Agent. I can help you with:
                - **Analysis**: Use keywords like "analyze" or "analysis"
                - **Summarization**: Use keywords like "summarize" or "summary"
                - **Transformation**: Use keywords like "transform" or "convert"
                
                Try rephrasing your request with one of these keywords!
                
                _Powered by Spring A2A Agent_
                """.formatted(message);
    }
}
