package com.example.a2aspring.executor;

import io.a2a.server.agentexecution.AgentExecutor;
import io.a2a.server.agentexecution.RequestContext;
import io.a2a.server.events.EventQueue;
import io.a2a.server.tasks.TaskUpdater;
import io.a2a.spec.InternalError;
import io.a2a.spec.JSONRPCError;
import io.a2a.spec.Message;
import io.a2a.spec.Part;
import io.a2a.spec.Task;
import io.a2a.spec.TaskNotCancelableError;
import io.a2a.spec.TaskState;
import io.a2a.spec.TextPart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Primary
public class SpringAgentExecutor implements AgentExecutor {

    private static final Logger LOGGER = LoggerFactory.getLogger(SpringAgentExecutor.class);

    @Override
    public void execute(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
        TaskUpdater updater = new TaskUpdater(context, eventQueue);
        
        try {
            LOGGER.info("Starting task execution - taskId: {}, contextId: {}", 
                    context.getTaskId(), context.getContextId());
            
            if (context.getTask() == null) {
                updater.submit();
                LOGGER.debug("Task submitted");
            }
            
            updater.startWork();
            LOGGER.debug("Task status changed to WORKING");
            
            String userMessage = extractTextFromMessage(context.getMessage());
            LOGGER.info("Processing user message: {}", userMessage);
            
            String result = processMessage(userMessage);
            
            List<Part<?>> parts = List.of(new TextPart(result, null));
            updater.addArtifact(parts, "response", "Agent Response", null);
            LOGGER.debug("Artifact added");
            
            updater.complete();
            LOGGER.info("Task completed successfully");
            
        } catch (JSONRPCError e) {
            LOGGER.error("JSONRPC error during task execution: {}", e.getMessage(), e);
            throw e;
        } catch (Exception e) {
            LOGGER.error("Unexpected error during task execution", e);
            throw new InternalError("Task execution failed: " + e.getMessage());
        }
    }

    @Override
    public void cancel(RequestContext context, EventQueue eventQueue) throws JSONRPCError {
        Task task = context.getTask();
        
        if (task == null) {
            throw new TaskNotCancelableError("Task not found");
        }
        
        TaskState currentState = task.getStatus().state();
        if (currentState.isFinal()) {
            throw new TaskNotCancelableError(
                    "Task cannot be canceled - current state: " + currentState.asString());
        }
        
        TaskUpdater updater = new TaskUpdater(context, eventQueue);
        updater.cancel();
        LOGGER.info("Task canceled - taskId: {}", context.getTaskId());
    }

    protected String processMessage(String message) {
        return "Processed: " + message + "\n\nThis response was generated by the Spring A2A Agent.";
    }

    private String extractTextFromMessage(Message message) {
        if (message == null || message.getParts() == null) {
            return "";
        }
        
        StringBuilder textBuilder = new StringBuilder();
        for (Part<?> part : message.getParts()) {
            if (part instanceof TextPart textPart) {
                textBuilder.append(textPart.getText());
            }
        }
        return textBuilder.toString();
    }
}
